name: Test and build preview packages

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
    - 'master'

jobs:
  buildDockerContainers:
    runs-on: "ubuntu-latest"
    env:
      DOCKER_ID: 'cmcquinn'
      GITHUB_ID: 'cmcquinn'
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      IMAGE_NAME: 'mk-cnc-cross-builder'
      PACKAGE_DIR: 'mkhal'
    strategy:
      matrix:
        image_tag: [amd64_8, amd64_9, amd64_10, arm64_9, arm64_10, armhf_8, armhf_9, armhf_10, i386_8, i386_9, i386_10]
      fail-fast: false

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
          path: mkcnc

    - name: Get machinekit-hal packages
      run: python scripts/get-mkhal-packages.py -i ${{ env.GITHUB_ID }} -t ${{ matrix.image_tag }} -o ${{ env.PACKAGE_DIR }}
      working-directory: mkcnc

    - name: Build Docker images
      run: scripts/build_debian_docker_image -p ${{ env.PACKAGE_DIR }} -i ${{ env.DOCKER_ID}} -r ${{ env.IMAGE_NAME }} -t ${{ matrix.image_tag }}
      working-directory: mkcnc

    - name: Login to Docker Hub
      run: docker login -u ${{ env.DOCKER_ID }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Push images to Docker Hub
      run: docker push ${{ env.DOCKER_ID }}/${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}

  testMachinekitCNC:
    runs-on: ubuntu-latest
    needs: buildDockerContainers
    env:
      IMAGE: 'cmcquinn/mk-cnc-cross-builder'
    strategy:
      matrix:
        image_tag: [amd64_8, amd64_9, amd64_10]

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.sha }}
        path: to_build

    - name: Test Machinekit code on AMD64
      run: scripts/build_docker -i ${{ env.IMAGE }} -t ${{ matrix.image_tag }} -c test
      working-directory: ./to_build

  buildMachinekitCNCPackages:
    runs-on: ubuntu-latest
    needs: buildDockerContainers
    env:
      IMAGE: 'cmcquinn/mk-cnc-cross-builder'
    strategy:
      matrix:
        # Jessie does not have a ARM64 build
        image_tag: [amd64_8, amd64_9, amd64_10, arm64_9, arm64_10, armhf_8, armhf_9, armhf_10, i386_9, i386_10]
        thread_flavor: [posix, rt-preempt, xenomai]
      fail-fast: false

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.sha }}
        path: to_build/mkcnc

    - name: Build Machinekit-CNC .deb package
      run: scripts/build_docker -i ${{ env.IMAGE }} -t ${{ matrix.image_tag }} -f ${{ matrix.thread_flavor }} -c deb
      working-directory: ./to_build/mkcnc

    - name: Print built files
      run: find . -depth -not \( -path "." -or -path "./mkcnc" -or -path "./mkcnc/*" \) -print0 | xargs -0 -I '{}' ls --color -d '{}'
      working-directory: ./to_build

    - name: Create output directory 
      run: mkdir ./machinekit-cnc-debian
    
    - name: Copy built files into output directory
      run: find ./to_build -depth -not \( -path "." -or -path "./to_build" -or -path "./to_build/mkcnc" -or -path "./to_build/mkcnc/*" \) -print0 | xargs -0 -t -I '{}' cp -v '{}' ./machinekit-cnc-debian

    - name: Upload the built artifacts
      uses: actions/upload-artifact@v1
      with:
        name: machinekit-cnc-debian-${{ matrix.image_tag }}-${{ github.sha}}
        path: machinekit-cnc-debian
       